# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logistic_project?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8080
